class AppLocale {
  static final Map<String, Map<String, String>> _values = {
    'EN': {
      // ── Config Screen ────────────────────────────────────────────────────
      'title': 'New Session',
      'total_questions': 'TOTAL QUESTIONS',
      'time_per_question': 'TIME PER QUESTION',
      'select_mode': 'SELECT MODE / TOPIC',
      'random_mix': 'Random Mix',
      'random_desc': 'Includes questions from all categories.',
      'intelligent_bias': 'Intelligent Bias',
      'bias_sub': 'Focus on weak areas',
      'start_random': 'Start Random Challenge',
      'start_linear': 'Start Linear Test',
      'start_weak': 'Start Weak Area Practice',
      'odd_man': 'Odd Man Out',
      'fig_match': 'Figure Match',
      'pattern': 'Pattern Compl.',
      'analogy': 'Analogy',
      'figure_match': 'Figure Match',
      'figure_series': 'Figure Series',
      'geo_completion': 'Geo Completion',
      'mirror_shape': 'Mirror Shape',
      'mirror_text': 'Mirror Text/Clock',
      'punch_hole': 'Punch Hole',
      'embedded': 'Embedded Figure',
      'practice_weak_card': 'Practice Weak Areas',
      'weak_topics': 'topics',
      'questions_label': 'questions',
      'hold_reset': 'Hold to reset progress',
      'reset_title': 'Reset progress?',
      'reset_body':
          'This will clear all saved bias weights and start fresh. Your weak area history will be lost.',
      'cancel': 'Cancel',
      'reset': 'Reset',

      // ── Quiz Screen ──────────────────────────────────────────────────────
      'find_the': 'FIND THE',
      'question_figure': 'Question Figure',
      'next_question': 'Next Question',
      'finish': 'Finish',
      'skip': 'Skip',
      'logic': 'Logic',
      'bias_weights': 'BIAS WEIGHTS',
      'show_bias': 'Coordinator: show bias chart',
      'hide_bias': 'Hide bias chart',
      'look_at': 'Look at Option...',
      'reviewing': 'Reviewing',
      'weak_area': 'Weak area',
      'times_up': "Time's up! Correct answer was Option",
      'skipped_msg': 'Skipped — correct answer is Option',
      'correct_msg': 'Correct! Well done.',
      'wrong_msg': 'Wrong — correct answer is Option',
      'skipped_count': 'skipped',

      // ── Topic labels for quiz header ─────────────────────────────────────
      'topic_pattern': 'PATTERN COMPLETION',
      'topic_mirror': 'MIRROR IMAGE',
      'topic_odd': 'ODD MAN OUT',
      'topic_analogy': 'ANALOGY',
      'topic_figmatch': 'FIGURE MATCH',
      'topic_series': 'FIGURE SERIES',
      'topic_geo': 'GEO COMPLETION',
      'topic_punch': 'PUNCH HOLE',
      'topic_embedded': 'EMBEDDED FIGURE',

      // ── Summary Screen ───────────────────────────────────────────────────
      'report_title': 'Session Summary',
      'score': 'Score',
      'accuracy': 'Accuracy',
      'time': 'Time',
      'performance': 'Performance by Topic',
      'correct': 'Correct',
      'incorrect': 'Incorrect',
      'analysis': 'Analysis',
      'home': 'Home',
      'practice_weak': 'Practice Weak Areas',
      'questions_correct': 'Questions Correct',
      'time_per_q': 'Time Per Question',
      'category_breakdown': 'Category Breakdown',
      'review_answers': 'Review Answers',
      'return_home': 'Return to Home',
      'no_weak_session': 'No Weak Areas This Session',
      'avg_per_q': 'Avg',
      'per_question': '/ question',
      'detailed_report': 'Detailed Report',
      'question_short': 'Q',
      'avg_time': 'Avg time',
      'minute_short': 'm',
      'second_short': 's',
      'how_you_did_by_topic': 'How you did by topic',
      'try_again': 'Try Again',
      'full_report': 'Full Report',
      'practice_weak_summary': 'Practice Weak Areas:',
      'limit_45s': 'Limit (45s)',
      'topic_badge_good': 'Good',
      'topic_badge_ok': 'OK',
      'topic_badge_retry': 'Retry',
      'correct_answer_is': 'Correct answer is Option',
      'wrong_answer_is': 'Wrong — correct answer is Option',
      'skipped_answer_is': 'Skipped — correct answer is Option',
      'skipped_label': 'skipped',
      'minutes_ago_suffix': ' m ago',
      'hours_ago_suffix': ' h ago',
      'days_ago_suffix': ' d ago',
      'excellent_headline': 'Outstanding!',
      'good_headline': 'Good Work!',
      'average_headline': 'Keep Going!',
      'needs_practice_headline': 'Keep Practicing!',
      'excellent_subtitle':
          'You got most of them right.\nExcellent performance!',
      'good_subtitle':
          'Solid effort. A little more\npractice and you\'ll ace it!',
      'average_subtitle':
          'You\'re getting there.\nPractice the weak topics below.',
      'needs_practice_subtitle':
          'Don\'t give up! Every session\nmakes you stronger.',

      // ── Review Screen ────────────────────────────────────────────────────
      'answer_review': 'Answer Review',
      'show_wrong': 'Show wrong answers only',
      'showing_wrong': 'Showing wrong answers — tap to show all',
      'all_correct': 'All answers were correct!',
      'no_wrong': 'No wrong answers to show.',
      'your_answer_right': 'Your answer ✓',
      'your_answer_wrong': 'Your answer',
      'list': 'List',

      // ── History Screen ───────────────────────────────────────────────────
      'session_history': 'Session History',
      'no_sessions': 'No sessions yet',
      'no_sessions_sub': 'Complete a quiz to see your history here.',
      'clear_history': 'Clear all history?',
      'clear_history_body':
          'All session records will be deleted. This cannot be undone.',
      'clear': 'Clear',
      'avg': 'avg',

      // ── Status labels ────────────────────────────────────────────────────
      'strong': 'Strong',
      'good': 'Good',
      'weak': 'Weak',
      'find_mirror': 'FIND THE MIRROR IMAGE',
      'find_match': 'FIND THE EXACT MATCH',
      'find_next': 'FIND THE NEXT FIGURE',
      'find_complete': 'COMPLETE THE FIGURE',
      'find_embedded': 'FIND THE EMBEDDED SHAPE',
      'find_unfolded': 'FIND THE UNFOLDED RESULT',
      'find_odd': 'FIND THE ODD ONE OUT',
      'no_detail_data': 'No question data for this session',
      'no_detail_data_sub':
          'Complete a new session to see full question review here.',
      // ── Category full names (summary/history) ────────────────────────────
      'cat_odd_man': 'Odd Man Out',
      'cat_fig_match': 'Figure Match',
      'cat_pattern': 'Pattern Completion',
      'cat_fig_series': 'Figure Series',
      'cat_analogy': 'Analogy',
      'cat_geo': 'Geo Completion',
      'cat_mirror_shape': 'Mirror Shape',
      'cat_mirror_text': 'Mirror Text',
      'cat_punch': 'Punch Hole',
      'cat_embedded': 'Embedded Figure',

      // ── Category short labels (history bar chart) ─────────────────────────
      'short_odd': 'Odd',
      'short_fig': 'Fig',
      'short_pattern': 'Pat',
      'short_series': 'Ser',
      'short_analogy': 'Ana',
      'short_geo': 'Geo',
      'short_mirshape': 'MirS',
      'short_mirtext': 'MirT',
      'short_punch': 'Pnc',
      'short_embedded': 'Emb',

      // ── Misc UI ───────────────────────────────────────────────────────────
      'time_unlimited': 'Unlimited',
      'time_label': 'Time',
      'weak_areas': 'Weak Areas',
      'clear_history_btn': 'Clear history',

      // ── Question renderer instructions ────────────────────────────────────
      'instr_match': 'Find the exact match',
      'instr_pattern': 'Find the missing figure to complete the pattern',
      'instr_series': 'What comes next in the series?',
      'instr_geo': 'Which piece completes this shape?',
      'instr_mirror': 'Find the mirror image',
      'instr_embedded':
          'Find the option that contains this shape hidden inside it',
      'instr_analogy': 'A : B :: C : ?  — Find D',
      'instr_error': 'Unable to generate — please skip this question.',
    },

    'MR': {
      // ── Config Screen ────────────────────────────────────────────────────
      'title': 'नवीन सत्र',
      'total_questions': 'एकूण प्रश्न',
      'time_per_question': 'प्रत्येक प्रश्नासाठी वेळ',
      'select_mode': 'विषय निवडा',
      'random_mix': 'मिश्र सराव',
      'random_desc': 'सर्व विषयांमधील प्रश्नांचा समावेश आहे.',
      'intelligent_bias': 'बुद्धिमान निवड',
      'bias_sub': 'कमकुवत क्षेत्रांवर लक्ष',
      'start_random': 'मिश्र सराव सुरू करा',
      'start_linear': 'रेखीय चाचणी सुरू करा',
      'start_weak': 'कमकुवत विषयांचा सराव सुरू करा',
      'odd_man': 'वेगळे पद ओळखा',
      'fig_match': 'समान आकृती',
      'pattern': 'आकृती पूर्ण करा',
      'analogy': 'समसंबंध',
      'figure_match': 'समान आकृती',
      'figure_series': 'आकृती मालिका',
      'geo_completion': 'भौमितिक पूर्तता',
      'mirror_shape': 'आरसा प्रतिमा',
      'mirror_text': 'अक्षर / घड्याळ आरसा',
      'punch_hole': 'छिद्र आकृती',
      'embedded': 'अंतर्भूत आकृती',
      'practice_weak_card': 'कमकुवत विषयांचा सराव',
      'weak_topics': 'विषय',
      'questions_label': 'प्रश्न',
      'hold_reset': 'प्रगती रीसेट करण्यासाठी दीर्घ दाबा',
      'reset_title': 'प्रगती रीसेट करायची का?',
      'reset_body':
          'यामुळे सर्व बायस वेट मिटतील आणि नव्याने सुरुवात होईल. कमकुवत विषयांचा इतिहास नष्ट होईल.',
      'cancel': 'रद्द करा',
      'reset': 'रीसेट',

      // ── Quiz Screen ──────────────────────────────────────────────────────
      'find_the': 'खालीलपैकी ओळखा',
      'question_figure': 'प्रश्न आकृती',
      'next_question': 'पुढचा प्रश्न',
      'finish': 'संपवा',
      'skip': 'वगळा',
      'logic': 'स्पष्टीकरण',
      'bias_weights': 'बायस वेट',
      'show_bias': 'समन्वयक: बायस चार्ट दाखवा',
      'hide_bias': 'बायस चार्ट लपवा',
      'look_at': 'पर्याय पाहा...',
      'reviewing': 'पुनरावलोकन',
      'weak_area': 'कमकुवत विषय',
      'times_up': 'वेळ संपला! बरोबर उत्तर पर्याय',
      'skipped_msg': 'वगळले — बरोबर उत्तर पर्याय',
      'correct_msg': 'बरोबर! शाबास.',
      'wrong_msg': 'चुकीचे — बरोबर उत्तर पर्याय',
      'skipped_count': 'वगळलेले',

      // ── Topic labels ─────────────────────────────────────────────────────
      'topic_pattern': 'आकृती पूर्णता',
      'topic_mirror': 'आरसा प्रतिमा',
      'topic_odd': 'वेगळे पद',
      'topic_analogy': 'समसंबंध',
      'topic_figmatch': 'समान आकृती',
      'topic_series': 'आकृती मालिका',
      'topic_geo': 'भौमितिक पूर्तता',
      'topic_punch': 'छिद्र आकृती',
      'topic_embedded': 'अंतर्भूत आकृती',

      // ── Summary Screen ───────────────────────────────────────────────────
      'report_title': 'सत्र सारांश',
      'score': 'गुण',
      'accuracy': 'अचूकता',
      'time': 'वेळ',
      'performance': 'विषयानुसार कामगिरी',
      'correct': 'बरोबर',
      'incorrect': 'चूक',
      'analysis': 'विश्लेषण',
      'home': 'मुख्य पृष्ठ',
      'practice_weak': 'कमकुवत विषयांचा सराव',
      'questions_correct': 'प्रश्न बरोबर',
      'time_per_q': 'प्रति प्रश्न वेळ',
      'category_breakdown': 'विषयनिहाय विश्लेषण',
      'review_answers': 'उत्तरे तपासा',
      'return_home': 'मुख्यपृष्ठावर परत',
      'no_weak_session': 'या सत्रात कोणते कमकुवत विषय नाहीत',
      'avg_per_q': 'सरासरी',
      'per_question': '/ प्रश्न',
      'detailed_report': 'तपशीलवार अहवाल',
      'question_short': 'प्र',
      'avg_time': 'सरासरी वेळ',
      'minute_short': 'मि',
      'second_short': 'से',
      'how_you_did_by_topic': 'विषयानुसार तुमची कामगिरी',
      'try_again': 'पुन्हा प्रयत्न करा',
      'full_report': 'पूर्ण अहवाल',
      'practice_weak_summary': 'कमकुवत विषयांचा सराव:',
      'limit_45s': 'मर्यादा (45 सेकंद)',
      'topic_badge_good': 'चांगले',
      'topic_badge_ok': 'ठीक',
      'topic_badge_retry': 'पुन्हा प्रयत्न',
      'correct_answer_is': 'बरोबर उत्तर पर्याय',
      'wrong_answer_is': 'चुकीचे — बरोबर उत्तर पर्याय',
      'skipped_answer_is': 'वगळले — बरोबर उत्तर पर्याय',
      'skipped_label': 'वगळलेले',
      'minutes_ago_suffix': ' मिनिटांपूर्वी',
      'hours_ago_suffix': ' तासांपूर्वी',
      'days_ago_suffix': ' दिवसांपूर्वी',
      'excellent_headline': 'अतिशय उत्कृष्ट!',
      'good_headline': 'छान काम!',
      'average_headline': 'पुढे चालू ठेवा!',
      'needs_practice_headline': 'अधिक सराव करा!',
      'excellent_subtitle':
          'तुम्ही बहुतेक प्रश्न बरोबर सोडवले.\nअतिशय उत्तम कामगिरी!',
      'good_subtitle':
          'छान प्रयत्न. थोडा अधिक\nसराव केला तर तुम्ही नक्की यशस्वी व्हाल!',
      'average_subtitle':
          'तुम्ही योग्य दिशेने जात आहात.\nखालील कमकुवत विषयांवर सराव करा.',
      'needs_practice_subtitle':
          'हार मानू नका! प्रत्येक सत्र\nतुम्हाला अधिक मजबूत बनवते.',

      // ── Review Screen ────────────────────────────────────────────────────
      'answer_review': 'उत्तर तपासणी',
      'show_wrong': 'फक्त चुकीची उत्तरे दाखवा',
      'showing_wrong': 'चुकीची उत्तरे दाखवत आहे — सर्व पाहण्यासाठी दाबा',
      'all_correct': 'सर्व उत्तरे बरोबर होती!',
      'no_wrong': 'दाखवण्यासारखी चुकीची उत्तरे नाहीत.',
      'your_answer_right': 'तुमचे उत्तर ✓',
      'your_answer_wrong': 'तुमचे उत्तर',
      'list': 'यादी',

      // ── History Screen ───────────────────────────────────────────────────
      'session_history': 'सत्र इतिहास',
      'no_sessions': 'अद्याप कोणते सत्र नाही',
      'no_sessions_sub': 'इतिहास पाहण्यासाठी एक चाचणी पूर्ण करा.',
      'clear_history': 'सर्व इतिहास मिटवायचा का?',
      'clear_history_body': 'सर्व सत्र नोंदी कायमस्वरूपी हटवल्या जातील.',
      'clear': 'मिटवा',
      'avg': 'सरासरी',

      // ── Status labels ────────────────────────────────────────────────────
      'strong': 'उत्तम',
      'good': 'चांगले',
      'weak': 'कमकुवत',
      'find_mirror': 'आरसा प्रतिमा शोधा',
      'find_match': 'समान आकृती शोधा',
      'find_next': 'पुढील आकृती शोधा',
      'find_complete': 'आकृती पूर्ण करा',
      'find_embedded': 'अंतर्भूत आकृती शोधा',
      'find_unfolded': 'उघडलेली आकृती शोधा',
      'find_odd': 'वेगळी आकृती शोधा',
      'no_detail_data': 'या सत्रासाठी प्रश्नांचा डेटा उपलब्ध नाही',
      'no_detail_data_sub': 'पूर्ण प्रश्न पुनरावलोकनासाठी नवीन सत्र पूर्ण करा.',
      // ── Category full names ───────────────────────────────────────────────
      'cat_odd_man': 'वेगळे पद',
      'cat_fig_match': 'समान आकृती',
      'cat_pattern': 'आकृती पूर्णता',
      'cat_fig_series': 'आकृती मालिका',
      'cat_analogy': 'समसंबंध',
      'cat_geo': 'भौमितिक पूर्तता',
      'cat_mirror_shape': 'आरसा आकृती',
      'cat_mirror_text': 'अक्षर आरसा',
      'cat_punch': 'छिद्र आकृती',
      'cat_embedded': 'अंतर्भूत आकृती',

      // ── Category short labels ─────────────────────────────────────────────
      'short_odd': 'वेग',
      'short_fig': 'आकृ',
      'short_pattern': 'पूर्ण',
      'short_series': 'माल',
      'short_analogy': 'सम',
      'short_geo': 'भौ',
      'short_mirshape': 'आर',
      'short_mirtext': 'अक्ष',
      'short_punch': 'छिद्र',
      'short_embedded': 'अंत',

      // ── Misc UI ───────────────────────────────────────────────────────────
      'time_unlimited': 'अमर्यादित',
      'time_label': 'वेळ',
      'weak_areas': 'कमकुवत विषय',
      'clear_history_btn': 'इतिहास मिटवा',

      // ── Question renderer instructions ────────────────────────────────────
      'instr_match': 'अचूक जुळणारी आकृती शोधा',
      'instr_pattern': 'आकृती पूर्ण करण्यासाठी चुकलेली आकृती शोधा',
      'instr_series': 'मालिकेत पुढे काय येते?',
      'instr_geo': 'कोणता तुकडा ही आकृती पूर्ण करतो?',
      'instr_mirror': 'आरसा प्रतिमा शोधा',
      'instr_embedded': 'या आकृतीला आतमध्ये लपवणारा पर्याय शोधा',
      'instr_analogy': 'A : B :: C : ?  — D शोधा',
      'instr_error': 'प्रश्न तयार करता आला नाही — हा प्रश्न वगळा.',
    },

    'HI': {
      // ── Config Screen ────────────────────────────────────────────────────
      'title': 'नया सत्र',
      'total_questions': 'कुल प्रश्न',
      'time_per_question': 'प्रति प्रश्न समय',
      'select_mode': 'मोड / विषय चुनें',
      'random_mix': 'सभी विषयों का मिश्रण',
      'random_desc': 'सभी विषयों के प्रश्न शामिल हैं।',
      'intelligent_bias': 'स्मार्ट बायस',
      'bias_sub': 'कमज़ोर क्षेत्रों पर ध्यान',
      'start_random': 'रैंडम अभ्यास शुरू करें',
      'start_linear': 'लाइनर टेस्ट शुरू करें',
      'start_weak': 'कमज़ोर क्षेत्रों का अभ्यास शुरू करें',
      'odd_man': 'अलग आकृति पहचानें',
      'fig_match': 'समान आकृति',
      'pattern': 'आकृति पूर्णता',
      'analogy': 'समानता',
      'figure_match': 'समान आकृति',
      'figure_series': 'आकृति श्रृंखला',
      'geo_completion': 'ज्यामितीय पूर्णता',
      'mirror_shape': 'दर्पण आकृति',
      'mirror_text': 'दर्पण अक्षर / घड़ी',
      'punch_hole': 'छेद आकृति',
      'embedded': 'अंतर्निहित आकृति',
      'practice_weak_card': 'कमज़ोर क्षेत्रों का अभ्यास',
      'weak_topics': 'विषय',
      'questions_label': 'प्रश्न',
      'hold_reset': 'रीसेट के लिए दबाकर रखें',
      'reset_title': 'प्रगति रीसेट करें?',
      'reset_body':
          'यह सभी बायस वेट साफ़ करेगा और नई शुरुआत करेगा। आपकी कमज़ोर क्षेत्रों की जानकारी मिट जाएगी।',
      'cancel': 'रद्द करें',
      'reset': 'रीसेट',

      // ── Quiz Screen ──────────────────────────────────────────────────────
      'find_the': 'ढूँढिए',
      'question_figure': 'प्रश्न आकृति',
      'next_question': 'अगला प्रश्न',
      'finish': 'समाप्त करें',
      'skip': 'छोड़ें',
      'logic': 'तर्क',
      'bias_weights': 'बायस वेट',
      'show_bias': 'समन्वयक: बायस चार्ट दिखाएँ',
      'hide_bias': 'बायस चार्ट छिपाएँ',
      'look_at': 'विकल्प देखें...',
      'reviewing': 'समीक्षा',
      'weak_area': 'कमज़ोर क्षेत्र',
      'times_up': 'समय समाप्त! सही उत्तर विकल्प',
      'skipped_msg': 'छोड़ा गया — सही उत्तर विकल्प',
      'correct_msg': 'सही! बहुत बढ़िया।',
      'wrong_msg': 'गलत — सही उत्तर विकल्प',
      'skipped_count': 'छोड़ा गया',

      // ── Topic labels for quiz header ─────────────────────────────────────
      'topic_pattern': 'आकृति पूर्णता',
      'topic_mirror': 'दर्पण आकृति',
      'topic_odd': 'अलग आकृति',
      'topic_analogy': 'समानता',
      'topic_figmatch': 'समान आकृति',
      'topic_series': 'आकृति श्रृंखला',
      'topic_geo': 'ज्यामितीय पूर्णता',
      'topic_punch': 'छेद आकृति',
      'topic_embedded': 'अंतर्निहित आकृति',

      // ── Summary Screen ───────────────────────────────────────────────────
      'report_title': 'सत्र सारांश',
      'score': 'स्कोर',
      'accuracy': 'सटीकता',
      'time': 'समय',
      'performance': 'विषयवार प्रदर्शन',
      'correct': 'सही',
      'incorrect': 'गलत',
      'analysis': 'विश्लेषण',
      'home': 'होम',
      'practice_weak': 'कमज़ोर क्षेत्रों का अभ्यास',
      'questions_correct': 'सही प्रश्न',
      'time_per_q': 'प्रति प्रश्न समय',
      'category_breakdown': 'श्रेणीवार विवरण',
      'review_answers': 'उत्तर देखें',
      'return_home': 'होम पर जाएँ',
      'no_weak_session': 'इस सत्र में कोई कमज़ोर क्षेत्र नहीं',
      'avg_per_q': 'औसत',
      'per_question': '/ प्रश्न',
      'detailed_report': 'विस्तृत रिपोर्ट',
      'question_short': 'प्र',
      'avg_time': 'औसत समय',
      'minute_short': 'मि',
      'second_short': 'से',
      'how_you_did_by_topic': 'विषयवार आपका प्रदर्शन',
      'try_again': 'फिर प्रयास करें',
      'full_report': 'पूरी रिपोर्ट',
      'practice_weak_summary': 'कमज़ोर क्षेत्रों का अभ्यास:',
      'limit_45s': 'सीमा (45 सेकंड)',
      'topic_badge_good': 'अच्छा',
      'topic_badge_ok': 'ठीक',
      'topic_badge_retry': 'फिर प्रयास',
      'correct_answer_is': 'सही उत्तर विकल्प',
      'wrong_answer_is': 'गलत — सही उत्तर विकल्प',
      'skipped_answer_is': 'छोड़ा गया — सही उत्तर विकल्प',
      'skipped_label': 'छोड़ा गया',
      'minutes_ago_suffix': ' मिनट पहले',
      'hours_ago_suffix': ' घंटे पहले',
      'days_ago_suffix': ' दिन पहले',
      'excellent_headline': 'बहुत शानदार!',
      'good_headline': 'अच्छा काम!',
      'average_headline': 'जारी रखें!',
      'needs_practice_headline': 'और अभ्यास करें!',
      'excellent_subtitle': 'आपने अधिकांश प्रश्न सही किए।\nबेहतरीन प्रदर्शन!',
      'good_subtitle':
          'अच्छा प्रयास। थोड़ा और\nअभ्यास करेंगे तो और बेहतर करेंगे!',
      'average_subtitle':
          'आप सही दिशा में हैं।\nनीचे दिए कमजोर विषयों का अभ्यास करें।',
      'needs_practice_subtitle':
          'हार मत मानिए! हर सत्र\nआपको और मजबूत बनाता है।',

      // ── Review Screen ────────────────────────────────────────────────────
      'answer_review': 'उत्तर समीक्षा',
      'show_wrong': 'केवल गलत उत्तर दिखाएँ',
      'showing_wrong': 'गलत उत्तर दिखा रहे हैं — सभी देखने के लिए टैप करें',
      'all_correct': 'सभी उत्तर सही थे!',
      'no_wrong': 'दिखाने के लिए कोई गलत उत्तर नहीं है।',
      'your_answer_right': 'आपका उत्तर ✓',
      'your_answer_wrong': 'आपका उत्तर',
      'list': 'सूची',

      // ── History Screen ───────────────────────────────────────────────────
      'session_history': 'सत्र इतिहास',
      'no_sessions': 'अभी कोई सत्र नहीं',
      'no_sessions_sub': 'इतिहास देखने के लिए एक क्विज़ पूरा करें।',
      'clear_history': 'सारा इतिहास साफ़ करें?',
      'clear_history_body': 'सभी सत्र रिकॉर्ड स्थायी रूप से हटा दिए जाएंगे।',
      'clear': 'साफ़ करें',
      'avg': 'औसत',

      // ── Status labels ────────────────────────────────────────────────────
      'strong': 'मज़बूत',
      'good': 'अच्छा',
      'weak': 'कमज़ोर',
      'find_mirror': 'दर्पण आकृति ढूँढिए',
      'find_match': 'सटीक समान आकृति ढूँढिए',
      'find_next': 'अगली आकृति ढूँढिए',
      'find_complete': 'आकृति पूरी कीजिए',
      'find_embedded': 'अंतर्निहित आकृति ढूँढिए',
      'find_unfolded': 'खुला हुआ परिणाम ढूँढिए',
      'find_odd': 'अलग आकृति ढूँढिए',
      'no_detail_data': 'इस सत्र के लिए प्रश्न डेटा नहीं है',
      'no_detail_data_sub':
          'पूरा प्रश्न पुनरावलोकन देखने के लिए नया सत्र पूरा करें।',
      // ── Category full names (summary/history) ────────────────────────────
      'cat_odd_man': 'अलग आकृति',
      'cat_fig_match': 'समान आकृति',
      'cat_pattern': 'आकृति पूर्णता',
      'cat_fig_series': 'आकृति श्रृंखला',
      'cat_analogy': 'समानता',
      'cat_geo': 'ज्यामितीय पूर्णता',
      'cat_mirror_shape': 'दर्पण आकृति',
      'cat_mirror_text': 'दर्पण अक्षर',
      'cat_punch': 'छेद आकृति',
      'cat_embedded': 'अंतर्निहित आकृति',

      // ── Category short labels (history bar chart) ─────────────────────────
      'short_odd': 'अल',
      'short_fig': 'आक',
      'short_pattern': 'पूर्ण',
      'short_series': 'श्रृ',
      'short_analogy': 'समा',
      'short_geo': 'ज्यो',
      'short_mirshape': 'दर्प',
      'short_mirtext': 'अक्ष',
      'short_punch': 'छेद',
      'short_embedded': 'अंत',

      // ── Misc UI ───────────────────────────────────────────────────────────
      'time_unlimited': 'असीमित',
      'time_label': 'समय',
      'weak_areas': 'कमज़ोर क्षेत्र',
      'clear_history_btn': 'इतिहास साफ़ करें',

      // ── Question renderer instructions ────────────────────────────────────
      'instr_match': 'सटीक समान आकृति ढूँढिए',
      'instr_pattern': 'पैटर्न पूरा करने के लिए लापता आकृति ढूँढिए',
      'instr_series': 'श्रृंखला में अगला क्या है?',
      'instr_geo': 'कौन-सा भाग यह आकृति पूरी करता है?',
      'instr_mirror': 'दर्पण आकृति ढूँढिए',
      'instr_embedded': 'ऐसा विकल्प ढूँढिए जिसमें यह आकृति छिपी हो',
      'instr_analogy': 'A : B :: C : ?  — D ढूँढिए',
      'instr_error': 'प्रश्न बन नहीं सका — यह प्रश्न छोड़ दें।',
    },
  };

  static String get(String lang, String key) {
    return _values[lang]?[key] ?? _values['EN']?[key] ?? key;
  }

  static String nextLang(String current) {
    const cycle = ['EN', 'MR', 'HI'];
    final idx = cycle.indexOf(current);
    return cycle[(idx + 1) % cycle.length];
  }

  static String langLabel(String lang) {
    const labels = {'EN': 'EN', 'MR': 'म', 'HI': 'हि'};
    return labels[lang] ?? lang;
  }

  // ── App-wide current language ───────────────────────────────────────────
  // Set this when user changes language in SessionConfigScreen.
  // All screens that don't receive lang explicitly can read from here.
  static String _current = 'EN';

  static String get current => _current;

  static void setLang(String lang) {
    if (_values.containsKey(lang)) _current = lang;
  }

  /// Shorthand — AppLocale.s('key') uses the app-wide current language
  static String s(String key) => get(_current, key);
}